### ISSUE TITLE
ChangeRequest_CR01

### ISSUE THREAD

**Issue by soesandanwe** [karpalSingh/Unit7CA2#1]
System/Product/Service Name:  Maintenance Panel

CHANGE DESCRIPTION:
- [ The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. ] 

- [Enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors. ] 

REASON FOR CHANGE:
The maintainer often complains that it is frustrating and time-consuming to manually calculate these amounts; some have given up calculating and others insist that the system displays erroneous amounts than what’s physically collected.

**Comment by karpalSingh** [comment]
Karpal and Evon is performing impact analysis for the change

**Comment by karpalSingh** [comment]
Karpal has completed impact analysis and has assigned to May Han for the execution of the change.

**Comment by SoeMayHan** [comment]
Committed the code with enhancement feature. Commit no abe282e.

**Comment by evonwoo84** [comment]
I have reviewed and ready for testing

**Comment by soepyae7** [comment]
@evonwoo84 I have tested the code and verified the enhancements.

**Comment by soesandanwe** [comment]
I already seen. It is good to go! Thanks! @SoeMayHan

**Comment by SoeMayHan** [comment]
UR accepted the change enhancement feature @karpalSingh for your action.

**Comment by karpalSingh** [comment]
This issue has been resolved.
