### ISSUE TITLE
ChangeRequest_CR02

### ISSUE THREAD

**Issue by soesandanwe** [karpalSingh/Unit7CA2#2]
System/Product/Service Name: Maintenance Panel

CHANGE DESCRIPTION:

[ Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushes “Press Here When Finished”. The simulation currently does not clear the values on the completion of a Maintenance session. Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected, persists in display.  ]

REASON FOR CHANGE:
It sometimes causes confusion to Maintainer.

**Comment by evonwoo84** [comment]
I have reviewed and acknowledged as defect

**Comment by soepyae7** [comment]
Hi @SoeMayHan, For your action.I have tested code and found the bug.

**Comment by SoeMayHan** [comment]
Bug fixed and committed. Commit Id -  3cda07d. Hi @soepyae7 , please test for this.

**Comment by soepyae7** [comment]
Hi @SoeMayHan, tested your committed version. 
Status- Pass

**Comment by soesandanwe** [comment]
Hi @SoeMayHan , I already tested. It is solved already. Thank You!

**Comment by SoeMayHan** [comment]
UR accepted the bug fixed. @karpalSingh  for your action.

**Comment by karpalSingh** [comment]
This issue has been resolved.
